(setq package-list '(
                     2048-game
                     ag
                     anaconda-mode
                     avy
                     company
                     company-php
                     diminish
                     dracula-theme
                     elfeed
                     elfeed-org
                     emmet-mode
                     exec-path-from-shell
                     flx
                     flycheck
                     go-mode
                     helm
                     helm-ag
                     helm-flx
                     helm-flycheck
                     helm-projectile
                     helm-swoop
                     ibuffer-git
                     ibuffer-vc
                     isend-mode
                     lorem-ipsum
                     magit
                     multiple-cursors
                     neotree
                     pdf-tools
                     php-mode
                     projectile
                     rainbow-delimiters
                     refine
                     request
                     smooth-scrolling
                     undo-tree
                     viking-mode
                     web-mode
                     which-key
                     whole-line-or-region
                     win-switch
                     xkcd
                     yasnippet
                     zzz-to-char
                     )
      )
